### ISSUE TITLE
Some tests failed

### ISSUE THREAD

**Issue by nagayev** [francois-berder/fat16#1]
I ran `sudo ./bin/run_test` and got this:
Test results:
<details>
<summary>Result</summary>
AppendSmallFileTest           FAIL      
DeleteFileTest                FAIL      
DeleteDirectoryTest           PASS      
FilenameTest                  PASS      
ReadEmptyFileTest             PASS      
ReadSmallFileTest             PASS      
WriteEraseContentTest         PASS      
WriteSmallFileTest            PASS      
WriteLargeFileTest (1024)     PASS      
WriteLargeFileTest (2047)     PASS      
WriteLargeFileTest (2048)     PASS      
WriteLargeFileTest (2049)     PASS      
WriteLargeFileTest (4097)     PASS      
WriteLargeFileTest (20481)    PASS      
ReadLargeFileTest (1024)      PASS      
ReadLargeFileTest (2047)      PASS      
ReadLargeFileTest (2048)      PASS      
ReadLargeFileTest (2049)      PASS      
ReadLargeFileTest (4097)      PASS      
ReadLargeFileTest (20481)     PASS      
LsTest / (0)                  PASS      
LsTest / (1)                  PASS      
LsTest / (128)                PASS      
LsTest / (256)                PASS      
LsTest / (511)                PASS      
LsTest / (512)                PASS      
LsTest /DATA (0)              PASS      
LsTest /DATA (1)              PASS      
LsTest /DATA (512)            PASS      
LsTest /DATA (2048)           PASS      
LsTest /IMAGES/PNG (2048)     PASS      
MkdirTest                     PASS      
RmdirTest                     PASS
</details>

**Comment by francois-berder** [comment]
Thank you @nagayev . I confirmed that testsAppendSmallFileTest and DeleteFileTest are failing.

**Comment by francois-berder** [comment]
Fixed by commit bf9bfb30197e5ff14cfad11197624a4640dc6ad7 and 9e2f599e35853bfef0f5e3d05be8d614cf723800
